spring:
  mail:
    host: smtp.163.com
    username: yuikimo@163.com
    password: KKYMCWNNJQWDKTCJ
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: konwocao
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    cors:
      origin: '*'
      credentials: false
      methods: '*'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭